version: '3.9'
services:
  mcp-sidecar:
    image: qingyanjiu/mcp-sidecar
    ports:
      - "2222:2222"
      - "9970:9970"
    command: ["sh", "-c", "sh start-server.sh"]
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - ai-agenic-network
    depends_on:
      - transcode-monitor

  agentic-app:
    image: qingyanjiu/langchain:1.0.3
    ports:
      - "8001:8001"
    networks:
      - ai-agenic-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    depends_on:
      - mcp-sidecar

networks:
  ai-agenic-network: