spring:
    application:
        name: ai-wrapper
    profiles:
        active: local

    ai:
        mcp:
            server:
                enabled: true
                protocol: STREAMABLE   # 推荐 Streamable‑HTTP 传输
                name: mcp-sidecar
                version: 1.0.0

    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
    redis:
        # 默认不使用redis
        enabled: false

management:
    server:
        port: 9970
    endpoint:
        health:
            show-details: always
    endpoints:
        enabled-by-default: true
        web:
            base-path: /actuator
            exposure:
                include: '*'

logging:
    file:
        name: logs/${spring.application.name}/info.log

mybatis-plus:
    type-handlers-package: com.hx.gd.typehandler
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations:
        - classpath:mappers/*.xml

server:
    compression:
        min-response-size: 1024
        enabled: true

springdoc:
    api-docs:
        enabled: true
        path: /v3/api-docs    # 默认即可，不建议改动，swagger UI 会自动请求这个地址
    swagger-ui:
        enabled: true
        path: /swagger-ui.html  # 默认UI路径
        operations-sorter: alpha   # 接口按字母排序
        tags-sorter: alpha         # tag排序
        display-request-duration: true  # 显示请求耗时

